version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8086:8086"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"   # NGINX uses port 80 inside the container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
